# Items used for branding
branding:
  title: "Isolat - Dashboard"
  parent: "COVID-19"
  description: "COVID-19 State and County Level Case and Plateau Prediction"
  imageUrl: ""
  aboutUrl: "https://github.com/yash-deshpande/isolat-public"
  appUrl: ""
  sourceUrl: "https://github.com/yash-deshpande/isolat-public"
  parentUrl: "https://github.com/reichlab/covid19-forecast-hub"
